name: house_price_prediction
description: A Flutter app for predicting house prices using machine learning
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  fluttertoast: ^8.2.12
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.1.0  # Keep this if you want to use Google Fonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/house_bg.png